# Generated by Django 3.1.3 on 2020-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0002_auto_20201125_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_message',
            name='time',
        ),
        migrations.AlterField(
            model_name='cliente_message',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
