# Generated by Django 3.1.3 on 2020-11-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0003_auto_20201125_1741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente_message',
            table='mensaje',
        ),
    ]
