# Generated by Django 3.1.3 on 2020-11-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0004_auto_20201125_1823'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente_contacto',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='cliente_message',
            table='Mensaje',
        ),
    ]
