# Generated by Django 3.1.3 on 2020-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0005_auto_20201126_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente_contacto',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='cliente_message',
            options={'verbose_name': 'Mensaje'},
        ),
        migrations.AlterModelTable(
            name='cliente_contacto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente_message',
            table=None,
        ),
    ]
